In [2]:
import yfinance as yf
import pandas as pd
import os

In [3]:
os.makedirs("../data", exist_ok=True)
print("Data folder is ready!")

Data folder is ready!

In [4]:
aapl = yf.download("AAPL", start="2020-01-01", end="2024-12-31")

aapl.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.400513  72.460776  71.156674  71.409778  135480400
2020-01-03  71.696632  72.455950  71.472454  71.629138  146322800
2020-01-06  72.267944  72.306514  70.568518  70.819216  118387200
2020-01-07  71.928040  72.533080  71.708680  72.277563  108872000
2020-01-08  73.085114  73.386431  71.631559  71.631559  132079200

In [5]:
print(aapl.shape)

(1257, 5)

In [6]:
print(aapl.isnull().sum())

Price   Ticker
Close   AAPL      0
High    AAPL      0
Low     AAPL      0
Open    AAPL      0
Volume  AAPL      0
dtype: int64

In [7]:
aapl.describe()

Price         Close         High          Low         Open        Volume
Ticker         AAPL         AAPL         AAPL         AAPL          AAPL
count   1257.000000  1257.000000  1257.000000  1257.000000  1.257000e+03
mean     151.439655   152.961786   149.740609   151.283476  9.061168e+07
std       41.816680    41.955068    41.591866    41.756218  5.324605e+07
min       54.213604    55.211520    51.372085    55.110038  2.323470e+07
25%      126.366203   127.451665   124.349242   125.840205  5.546960e+07
50%      150.080338   151.830411   148.084700   149.906081  7.629970e+07
75%      175.908401   177.608481   174.476819   175.755177  1.077601e+08
max      257.612701   258.686851   256.230269   256.787224  4.265100e+08

In [8]:
tickers = ["AAPL", "TSLA", "MSFT", "GOOGL", "AMZN"]
for ticker in tickers:
    print(f"Downloading {ticker}...")
    df = yf.download(ticker, start="2020-01-01", end="2024-12-31")
    df.to_csv(f"../data/{ticker}.csv")
    print(f"{ticker} saved!")
print("\n All done!")

Downloading AAPL...

[*********************100%***********************]  1 of 1 completed

AAPL saved!
Downloading TSLA...

[*********************100%***********************]  1 of 1 completed

TSLA saved!
Downloading MSFT...

[*********************100%***********************]  1 of 1 completed

MSFT saved!
Downloading GOOGL...

[*********************100%***********************]  1 of 1 completed

GOOGL saved!
Downloading AMZN...

[*********************100%***********************]  1 of 1 completed

AMZN saved!

 All done!

In [9]:
test = pd.read_csv("../data/AAPL.csv", index_col=0, parse_dates=True, skiprows=[1,2])
print(f"Rows: {len(test)}")
print(f"Date range: {test.index.min()} to {test.index.max()}")
test.head()

Rows: 1257
Date range: 2020-01-02 00:00:00 to 2024-12-30 00:00:00

                Close       High        Low       Open     Volume
Price
2020-01-02  72.400513  72.460776  71.156674  71.409778  135480400
2020-01-03  71.696632  72.455950  71.472454  71.629138  146322800
2020-01-06  72.267944  72.306514  70.568518  70.819216  118387200
2020-01-07  71.928040  72.533080  71.708680  72.277563  108872000
2020-01-08  73.085114  73.386431  71.631559  71.631559  132079200